name: pesoros_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  nik_validator: ^1.1.2
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  http: ^0.13.4
  fl_chart: ^0.55.0
  calendar_view: ^0.0.5
  syncfusion_flutter_maps: 20.1.47
  syncfusion_flutter_core: 20.1.47
  assets_audio_player: 3.0.4
  mini_music_visualizer: ^1.0.2
  blur: ^3.1.0
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

